/**
 * Dan Harmon's Story Circle — the macro-structure layer.
 *
 * Story Logic judges the joint between two beats; nothing in it can see that a
 * script has no second act. The circle is the complementary altitude: where each
 * scene sits in the eight-step arc, and therefore whether the arc is whole.
 *
 * Division of labour, deliberately: **the model assigns steps, this file judges
 * proportions.** Every number a writer is shown — "Search occupies 41% of your
 * pages" — is computed here from the assignments, never generated by Gemini. A
 * hallucinated percentage would be quoted in a pitch and be wrong.
 */

export type CircleStep = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const STEP_NAMES: Record<CircleStep, { key: string; gloss: string }> = {
  1: { key: 'You', gloss: 'establish the protagonist' },
  2: { key: 'Need', gloss: "something isn't right" },
  3: { key: 'Go', gloss: 'crossing the threshold' },
  4: { key: 'Search', gloss: 'the road of trials' },
  5: { key: 'Find', gloss: 'meeting the goddess' },
  6: { key: 'Take', gloss: 'paying the price' },
  7: { key: 'Return', gloss: 'bringing it home' },
  8: { key: 'Change', gloss: 'master of both worlds' },
};

/** Steps 1-2 and 7-8 sit in the ordered world; 3-6 in chaos. */
export function isChaos(step: CircleStep): boolean {
  return step >= 3 && step <= 6;
}

/**
 * Conventional share of screen time per step. These are rules of thumb, not law —
 * which is why every derived flag is accept/dismiss like any other.
 */
export const EXPECTED_SHARE: Record<CircleStep, number> = {
  1: 0.1,
  2: 0.1,
  3: 0.05,
  4: 0.25,
  5: 0.15,
  6: 0.15,
  7: 0.1,
  8: 0.1,
};

export interface SceneAssignment {
  sceneId: string;
  index: number;
  step: CircleStep;
  /** Relative screen time. Estimated page weight, or 1 if unknown. */
  weight: number;
}

export interface CircleDiagnostic {
  kind: 'missing_step' | 'disproportionate' | 'late_threshold' | 'compressed_return' | 'out_of_order';
  severity: 'info' | 'warn' | 'critical';
  step?: CircleStep;
  message: string;
}

export interface CircleAnalysis {
  /** Share of total weight per step, 0..1. */
  shares: Record<CircleStep, number>;
  /** Cumulative share at which the script first enters chaos (step 3). */
  goThreshold: number | null;
  /** Cumulative share at which it returns to order (step 7). */
  returnThreshold: number | null;
  diagnostics: CircleDiagnostic[];
}

const ALL_STEPS: CircleStep[] = [1, 2, 3, 4, 5, 6, 7, 8];

/** Below this many scenes, proportion complaints are noise rather than signal. */
const MIN_SCENES_FOR_PROPORTION = 8;

const pct = (n: number) => `${Math.round(n * 100)}%`;

export function analyzeCircle(assignments: SceneAssignment[]): CircleAnalysis {
  const shares = Object.fromEntries(ALL_STEPS.map((s) => [s, 0])) as Record<CircleStep, number>;

  const total = assignments.reduce((sum, a) => sum + Math.max(0, a.weight), 0);
  if (total === 0 || assignments.length === 0) {
    return { shares, goThreshold: null, returnThreshold: null, diagnostics: [] };
  }

  for (const a of assignments) shares[a.step] += Math.max(0, a.weight) / total;

  const ordered = [...assignments].sort((a, b) => a.index - b.index);

  /** Cumulative share of the script consumed before the first scene of `step`. */
  const thresholdOf = (step: CircleStep): number | null => {
    let cumulative = 0;
    for (const a of ordered) {
      if (a.step === step) return cumulative;
      cumulative += Math.max(0, a.weight) / total;
    }
    return null;
  };

  const goThreshold = thresholdOf(3);
  const returnThreshold = thresholdOf(7);

  const diagnostics: CircleDiagnostic[] = [];

  // --- missing steps ---
  for (const step of ALL_STEPS) {
    if (shares[step] > 0) continue;
    const { key, gloss } = STEP_NAMES[step];
    diagnostics.push({
      kind: 'missing_step',
      // A missing Take or Change is a structural hole; a missing Go is usually
      // an assignment artefact on a short script.
      severity: step === 6 || step === 8 ? 'critical' : 'warn',
      step,
      message:
        step === 6
          ? 'No scene pays a price (step 6, Take). Your protagonist gets what they want for free.'
          : step === 8
            ? 'No scene shows the protagonist changed (step 8, Change). The journey leaves no mark.'
            : `No scene occupies step ${step}, ${key} — ${gloss}.`,
    });
  }

  // --- disproportionate steps ---
  if (assignments.length >= MIN_SCENES_FOR_PROPORTION) {
    for (const step of ALL_STEPS) {
      const actual = shares[step];
      if (actual === 0) continue; // already reported as missing
      const expected = EXPECTED_SHARE[step];
      const ratio = actual / expected;
      const { key } = STEP_NAMES[step];

      if (ratio >= 1.6) {
        diagnostics.push({
          kind: 'disproportionate',
          severity: ratio >= 2.2 ? 'warn' : 'info',
          step,
          message: `${key} occupies ${pct(actual)} of the script; the convention is about ${pct(expected)}.`,
        });
      } else if (ratio <= 0.5) {
        diagnostics.push({
          kind: 'disproportionate',
          severity: 'info',
          step,
          message: `${key} occupies only ${pct(actual)} of the script; the convention is about ${pct(expected)}.`,
        });
      }
    }
  }

  // --- late threshold ---
  const EXPECTED_GO = EXPECTED_SHARE[1] + EXPECTED_SHARE[2]; // 20%
  if (goThreshold !== null && goThreshold > EXPECTED_GO * 1.75) {
    diagnostics.push({
      kind: 'late_threshold',
      severity: 'warn',
      step: 3,
      message: `The story crosses into chaos (Go) ${pct(goThreshold)} of the way in; the convention is about ${pct(EXPECTED_GO)}. That is the slow-start note.`,
    });
  }

  // --- compressed return ---
  const returnShare = shares[7] + shares[8];
  const expectedReturn = EXPECTED_SHARE[7] + EXPECTED_SHARE[8];
  if (returnShare > 0 && returnShare < expectedReturn * 0.5) {
    diagnostics.push({
      kind: 'compressed_return',
      severity: 'warn',
      message: `Return and Change together occupy ${pct(returnShare)}; the convention is about ${pct(expectedReturn)}. The transformation is asserted rather than dramatised.`,
    });
  }

  // --- out of order ---
  // Report only a scene that sits before an earlier-numbered step's territory,
  // which usually means a misplaced beat rather than a flashback.
  let highWater: CircleStep = 1;
  for (const a of ordered) {
    if (a.step < highWater - 1) {
      diagnostics.push({
        kind: 'out_of_order',
        severity: 'info',
        step: a.step,
        message: `Scene ${a.index + 1} reads as ${STEP_NAMES[a.step].key} (step ${a.step}) but arrives after step ${highWater}.`,
      });
    }
    if (a.step > highWater) highWater = a.step;
  }

  return { shares, goThreshold, returnThreshold, diagnostics };
}

/**
 * Estimate a scene's screen time in pages. Screenplay convention is roughly one
 * page per minute, and a page holds on the order of 800 characters of mixed
 * action and dialogue. Crude, but far better than counting every scene equally —
 * a half-page beat and a six-page confrontation are not the same weight.
 */
export function estimatePageWeight(text: string): number {
  return Math.max(0.1, text.length / 800);
}
